# Generated by Django 3.2.8 on 2021-11-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitna_web_app', '0002_alter_dataset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ('dataset_file',)},
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='dataset',
            new_name='dataset_file',
        ),
    ]
